# config/qdrant-config.yaml
service:
  http_port: 6333
  grpc_port: 6334
  enable_cors: true

storage:
  # Storage settings
  performance:
    max_search_threads: 0
  
  # Optimizations
  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0

# Cluster settings (for future scaling)
cluster:
  enabled: false

# Telemetry
telemetry_disabled: true